version: '3.8'

services:
  app:
    container_name: fiscus_fullstack
    build: .
    restart: always
    ports:
      - '10010:3000'
    environment:
      - DATABASE_URL=
      - NEXTAUTH_URL=
      - NEXTAUTH_SECRET=