version: '3.8'

services:
  fiscus_fullstack_image:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: fiscus_fullstack
    image: johedotcom/fiscus-fullstack-repository:latest
    restart: always
    ports:
      - '10010:3000'